export let SupplierRcvSummaryReportData = {
  data: {
    results: [
      {
        supplier_id: 1,
        supplier_name: "ACI",
        purchases: [
          {
            purchase_id: "POP2306250001",
            purchase_order_placed_id: 202,
            purchase_reference: "PO2306250001",
            purchase_date: "2025-06-23",
            purchase_time: "2025-06-23T03:35:17.187974Z",
            posted_by: "HasanAdmin",
            purchase_additional_commission: 0,
            purchase_product_cpu: 95.75,
            purchase_received_quantity_in_pcs: 87,
            purchase_bonus_quantity_in_pcs: 0,
            purchase_total_quantity_in_pcs: 87,
            purchase_vat: 0,
            purchase_value_at_cost: 237.25,
            purchase_net_purchase_value: 237.25,
          },
          {
            purchase_id: "POP2506250001",
            purchase_order_placed_id: 203,
            purchase_reference: "PO1906250013",
            purchase_date: "2025-06-25",
            purchase_time: "2025-06-25T11:14:13.663895Z",
            posted_by: "SiamAnzir",
            purchase_additional_commission: 0,
            purchase_product_cpu: 340,
            purchase_received_quantity_in_pcs: 22,
            purchase_bonus_quantity_in_pcs: 0,
            purchase_total_quantity_in_pcs: 22,
            purchase_vat: 9,
            purchase_value_at_cost: 1400,
            purchase_net_purchase_value: 1409,
          },
          {
            purchase_id: "POP2206250001",
            purchase_order_placed_id: 201,
            purchase_reference: "PO2206250002",
            purchase_date: "2025-06-22",
            purchase_time: "2025-06-22T05:46:48.065984Z",
            posted_by: "HasanAdmin",
            purchase_additional_commission: 0,
            purchase_product_cpu: 80.5,
            purchase_received_quantity_in_pcs: 46,
            purchase_bonus_quantity_in_pcs: 0,
            purchase_total_quantity_in_pcs: 46,
            purchase_vat: 0,
            purchase_value_at_cost: 126.25,
            purchase_net_purchase_value: 126.25,
          },
          {
            purchase_id: "POP1906250010",
            purchase_order_placed_id: 200,
            purchase_reference: "PO1906250014",
            purchase_date: "2025-06-19",
            purchase_time: "2025-06-19T09:41:29.693178Z",
            posted_by: "HasanAdmin",
            purchase_additional_commission: 0,
            purchase_product_cpu: 585,
            purchase_received_quantity_in_pcs: 1169,
            purchase_bonus_quantity_in_pcs: 0,
            purchase_total_quantity_in_pcs: 1169,
            purchase_vat: 0,
            purchase_value_at_cost: 2812.5,
            purchase_net_purchase_value: 2812.5,
          },
          {
            purchase_id: "POP1906250003",
            purchase_order_placed_id: 193,
            purchase_reference: "Purchased for Warehouse",
            purchase_date: "2025-06-19",
            purchase_time: "2025-06-19T07:26:31.648977Z",
            posted_by: "SazzadAdmin",
            purchase_additional_commission: 0,
            purchase_product_cpu: 0,
            purchase_received_quantity_in_pcs: 5,
            purchase_bonus_quantity_in_pcs: 5,
            purchase_total_quantity_in_pcs: 10,
            purchase_vat: 0,
            purchase_value_at_cost: 0,
            purchase_net_purchase_value: 0,
          },
          {
            purchase_id: "POP1906250004",
            purchase_order_placed_id: 194,
            purchase_reference: "Purchased for Warehouse",
            purchase_date: "2025-06-19",
            purchase_time: "2025-06-19T07:27:03.669453Z",
            posted_by: "SazzadAdmin",
            purchase_additional_commission: 0,
            purchase_product_cpu: 0,
            purchase_received_quantity_in_pcs: 5,
            purchase_bonus_quantity_in_pcs: 5,
            purchase_total_quantity_in_pcs: 10,
            purchase_vat: 0,
            purchase_value_at_cost: 0,
            purchase_net_purchase_value: 0,
          },
          {
            purchase_id: "POP1906250005",
            purchase_order_placed_id: 195,
            purchase_reference: "Purchased for Warehouse",
            purchase_date: "2025-06-19",
            purchase_time: "2025-06-19T07:29:38.594650Z",
            posted_by: "SazzadAdmin",
            purchase_additional_commission: 0,
            purchase_product_cpu: 0,
            purchase_received_quantity_in_pcs: 5,
            purchase_bonus_quantity_in_pcs: 5,
            purchase_total_quantity_in_pcs: 10,
            purchase_vat: 0,
            purchase_value_at_cost: 0,
            purchase_net_purchase_value: 0,
          },
          {
            purchase_id: "POP1906250006",
            purchase_order_placed_id: 196,
            purchase_reference: "Purchased for Warehouse",
            purchase_date: "2025-06-19",
            purchase_time: "2025-06-19T07:30:09.839414Z",
            posted_by: "SazzadAdmin",
            purchase_additional_commission: 0,
            purchase_product_cpu: 5.38,
            purchase_received_quantity_in_pcs: 200,
            purchase_bonus_quantity_in_pcs: 5,
            purchase_total_quantity_in_pcs: 205,
            purchase_vat: 0,
            purchase_value_at_cost: 1103.7,
            purchase_net_purchase_value: 1103.7,
          },
          {
            purchase_id: "POP1906250007",
            purchase_order_placed_id: 197,
            purchase_reference: "Purchased for Warehouse",
            purchase_date: "2025-06-19",
            purchase_time: "2025-06-19T07:31:53.251567Z",
            posted_by: "SazzadAdmin",
            purchase_additional_commission: 0,
            purchase_product_cpu: 5.38,
            purchase_received_quantity_in_pcs: 200,
            purchase_bonus_quantity_in_pcs: 5,
            purchase_total_quantity_in_pcs: 205,
            purchase_vat: 0,
            purchase_value_at_cost: 1103.7,
            purchase_net_purchase_value: 1103.7,
          },
          {
            purchase_id: "POP1906250008",
            purchase_order_placed_id: 198,
            purchase_reference: "Purchased for Warehouse",
            purchase_date: "2025-06-19",
            purchase_time: "2025-06-19T07:47:07.039187Z",
            posted_by: "SazzadAdmin",
            purchase_additional_commission: 0,
            purchase_product_cpu: 3.4,
            purchase_received_quantity_in_pcs: 20,
            purchase_bonus_quantity_in_pcs: 5,
            purchase_total_quantity_in_pcs: 25,
            purchase_vat: 0,
            purchase_value_at_cost: 84.9,
            purchase_net_purchase_value: 84.9,
          },
          {
            purchase_id: "POP1906250009",
            purchase_order_placed_id: 199,
            purchase_reference: "Purchased for Warehouse",
            purchase_date: "2025-06-19",
            purchase_time: "2025-06-19T08:35:19.777240Z",
            posted_by: "SazzadAdmin",
            purchase_additional_commission: 0,
            purchase_product_cpu: 3.4,
            purchase_received_quantity_in_pcs: 20,
            purchase_bonus_quantity_in_pcs: 5,
            purchase_total_quantity_in_pcs: 25,
            purchase_vat: 0,
            purchase_value_at_cost: 84.9,
            purchase_net_purchase_value: 84.9,
          },
          {
            purchase_id: "POP1906250002",
            purchase_order_placed_id: 192,
            purchase_reference: "Purchased for Warehouse",
            purchase_date: "2025-06-19",
            purchase_time: "2025-06-19T07:14:50.847429Z",
            posted_by: "SazzadAdmin",
            purchase_additional_commission: 0,
            purchase_product_cpu: 5.66,
            purchase_received_quantity_in_pcs: 5,
            purchase_bonus_quantity_in_pcs: 0,
            purchase_total_quantity_in_pcs: 5,
            purchase_vat: 0,
            purchase_value_at_cost: 28.3,
            purchase_net_purchase_value: 28.3,
          },
        ],
        supplier_additional_commission: 0,
        supplier_product_cpu: 1124.47,
        supplier_received_quantity_in_pcs: 1784,
        supplier_bonus_quantity_in_pcs: 35,
        supplier_total_quantity_in_pcs: 1819,
        supplier_value_at_cost: 6981.5,
        supplier_purchase_vat: 9,
        supplier_net_purchase_value: 6990.5,
      },
      {
        supplier_id: 4,
        supplier_name: "A B GROUP",
        purchases: [
          {
            purchase_id: "POP1906250001",
            purchase_order_placed_id: 191,
            purchase_reference: "QA Testing Purpose",
            purchase_date: "2025-06-19",
            purchase_time: "2025-06-19T06:52:25.449896Z",
            posted_by: "Shanto Kumar Saha",
            purchase_additional_commission: 0,
            purchase_product_cpu: 1835.6,
            purchase_received_quantity_in_pcs: 84500,
            purchase_bonus_quantity_in_pcs: 510,
            purchase_total_quantity_in_pcs: 85010,
            purchase_vat: 0,
            purchase_value_at_cost: 1637800,
            purchase_net_purchase_value: 1637800,
          },
        ],
        supplier_additional_commission: 0,
        supplier_product_cpu: 1835.6,
        supplier_received_quantity_in_pcs: 84500,
        supplier_bonus_quantity_in_pcs: 510,
        supplier_total_quantity_in_pcs: 85010,
        supplier_value_at_cost: 1637800,
        supplier_purchase_vat: 0,
        supplier_net_purchase_value: 1637800,
      },
    ],
  },
  status: 200,
  statusText: "OK",
  headers: {
    "content-length": "6796",
    "content-type": "application/json",
  },
  config: {
    transitional: {
      silentJSONParsing: true,
      forcedJSONParsing: true,
      clarifyTimeoutError: false,
    },
    adapter: ["xhr", "http"],
    transformRequest: [null],
    transformResponse: [null],
    timeout: 0,
    xsrfCookieName: "XSRF-TOKEN",
    xsrfHeaderName: "X-XSRF-TOKEN",
    maxContentLength: -1,
    maxBodyLength: -1,
    env: {},
    headers: {
      Accept: "application/json, text/plain, */*",
      Authorization:
        "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzUwOTk3MDc2LCJpYXQiOjE3NTA4MjM3ODgsImp0aSI6Ijk3M2Q5MDk1YTZiYTQzZTJhMDc5YmVjNmIxYzA0MDU5IiwidXNlcl9pZCI6NDY1Mn0.oflcsIBdtdGTgLXHA-J7gpMdxY6ndCEapbsaoSXJ4Ns",
    },
    method: "get",
    url: "http://192.168.10.219:8000/api/v2/report/purchase-order/supplier-wise-purchase-report/?purchase_summary=true&from_date=2025-06-19&to_date=2025-06-26",
  },
  request: {},
};

export let SupplierRcvSummaryReportTitle =
  "Supplier Wise Purchase Receiving Summary";
