import SupplierRcvReportPdf from "../../utils/careboxPdf/SupplierRcvReportPdf";
import { generatePdfSample } from "../../utils/pdf/generatePdfSample9";

let data = {
  data: {
    results: [
      {
        supplier_id: 1,
        supplier_name: "ACI",
        purchases: [
          {
            purchase_id: "POP1706250005",
            purchase_order_placed_id: 189,
            purchase_reference: "PO1706250004",
            purchase_date: "2025-06-17",
            purchase_time: "06:58:14.990962",
            posted_by: "HasanAdmin",
            additional_commission: 0,
            quantity: 2,
            bonus_quantity: 0,
            total_quantity: 2,
            products: [
              {
                product_name: "CADBURY DAIRY MILK  SILK BUBBLY CHOCOLATE-50 GM",
                product_id: 11143,
                generic_name: "CHOCOLATE",
                product_barcode: "7622201757991",
                product_unit: "50 GM",
                product_category: null,
                product_sub_category: null,
                product_location: "food",
                dosage_form_name: null,
                dosage_strength: null,
                variations: null,
                batch_number: "CB1706252506",
                batch_name: "CB1706252506",
                sku_number: "SKU1706250007",
                product_cpu: 50,
                received_quantity: 2,
                purchase_vat: 0,
                value_at_cost: 100,
                net_purchase_value: 100,
              },
            ],
            total_value_at_cost: 0,
            total_received_quantity: 0,
            total_product_cpu: 0,
            total_net_purchase_value: 0,
            total_purchase_vat: 0,
          },
          {
            purchase_id: "POP1706250006",
            purchase_order_placed_id: 190,
            purchase_reference: "PO1706250005",
            purchase_date: "2025-06-17",
            purchase_time: "07:08:17.874182",
            posted_by: "HasanAdmin",
            additional_commission: 0,
            quantity: 2,
            bonus_quantity: 0,
            total_quantity: 2,
            products: [
              {
                product_name: "CADBURY DAIRY MILK  SILK BUBBLY CHOCOLATE-50 GM",
                product_id: 11143,
                generic_name: "CHOCOLATE",
                product_barcode: "7622201757991",
                product_unit: "50 GM",
                product_category: null,
                product_sub_category: null,
                product_location: "food",
                dosage_form_name: null,
                dosage_strength: null,
                variations: null,
                batch_number: "CB1706252507",
                batch_name: "CB1706252507",
                sku_number: "SKU1706250008",
                product_cpu: 50,
                received_quantity: 2,
                purchase_vat: 0,
                value_at_cost: 100,
                net_purchase_value: 100,
              },
            ],
            total_value_at_cost: 0,
            total_received_quantity: 0,
            total_product_cpu: 0,
            total_net_purchase_value: 0,
            total_purchase_vat: 0,
          },
          {
            purchase_id: "POP1706250003",
            purchase_order_placed_id: 186,
            purchase_reference: "PO1706250003",
            purchase_date: "2025-06-17",
            purchase_time: "06:28:04.726089",
            posted_by: "HasanAdmin",
            additional_commission: 0,
            quantity: 2,
            bonus_quantity: 0,
            total_quantity: 2,
            products: [
              {
                product_name: "CADBURY DAIRY MILK  SILK BUBBLY CHOCOLATE-50 GM",
                product_id: 11143,
                generic_name: "CHOCOLATE",
                product_barcode: "7622201757991",
                product_unit: "50 GM",
                product_category: null,
                product_sub_category: null,
                product_location: "food",
                dosage_form_name: null,
                dosage_strength: null,
                variations: null,
                batch_number: "CB1706252503",
                batch_name: "CB1706252503",
                sku_number: "SKU1706250004",
                product_cpu: 50,
                received_quantity: 2,
                purchase_vat: 0,
                value_at_cost: 100,
                net_purchase_value: 100,
              },
            ],
            total_value_at_cost: 0,
            total_received_quantity: 0,
            total_product_cpu: 0,
            total_net_purchase_value: 0,
            total_purchase_vat: 0,
          },
          {
            purchase_id: "POP1706250004",
            purchase_order_placed_id: 187,
            purchase_reference: "PO1706250004",
            purchase_date: "2025-06-17",
            purchase_time: "06:57:39.427509",
            posted_by: "HasanAdmin",
            additional_commission: 0,
            quantity: 2,
            bonus_quantity: 0,
            total_quantity: 2,
            products: [
              {
                product_name: "CADBURY DAIRY MILK  SILK BUBBLY CHOCOLATE-50 GM",
                product_id: 11143,
                generic_name: "CHOCOLATE",
                product_barcode: "7622201757991",
                product_unit: "50 GM",
                product_category: null,
                product_sub_category: null,
                product_location: "food",
                dosage_form_name: null,
                dosage_strength: null,
                variations: null,
                batch_number: "CB1706252504",
                batch_name: "CB1706252504",
                sku_number: "SKU1706250005",
                product_cpu: 50,
                received_quantity: 2,
                purchase_vat: 0,
                value_at_cost: 100,
                net_purchase_value: 100,
              },
            ],
            total_value_at_cost: 0,
            total_received_quantity: 0,
            total_product_cpu: 0,
            total_net_purchase_value: 0,
            total_purchase_vat: 0,
          },
          {
            purchase_id: "POP1906250010",
            purchase_order_placed_id: 200,
            purchase_reference: "PO1906250014",
            purchase_date: "2025-06-19",
            purchase_time: "09:41:29.693178",
            posted_by: "HasanAdmin",
            additional_commission: 0,
            quantity: 2,
            bonus_quantity: 0,
            total_quantity: 2,
            products: [
              {
                product_name:
                  "Bhojon Roshik Package-Please Follow Description For Package Details.",
                product_id: 11226,
                generic_name: "Test Generic",
                product_barcode: "117ebe6d4fdd4",
                product_unit: "Please Follow Description For Package Details.",
                product_category: "Bazar Sodai",
                product_sub_category: "Rice",
                product_location: "food",
                dosage_form_name: null,
                dosage_strength: null,
                variations: [
                  {
                    variation_name: "Bhojon Roshik Package-Box-Red",
                    variation_id: "PVI0603250004",
                    is_default_variation: true,
                    qty_in_pcs: 0,
                    batch_number: "test2",
                    batch_name: "test2",
                    sku_number: "SKU1906250027",
                    product_cpu: 250,
                    received_quantity: 2,
                    purchase_vat: 0,
                    value_at_cost: 500,
                    net_purchase_value: 500,
                  },
                  {
                    variation_name: "Bhojon Roshik Package-Box-White",
                    variation_id: "PVI0603250003",
                    is_default_variation: false,
                    qty_in_pcs: 0,
                    batch_number: "test2",
                    batch_name: "test2",
                    sku_number: "SKU1906250028",
                    product_cpu: 250,
                    received_quantity: 1,
                    purchase_vat: 0,
                    value_at_cost: 250,
                    net_purchase_value: 250,
                  },
                ],
                value_at_cost: 0,
                net_purchase_value: 0,
              },
              {
                product_name: "Alatrol-10 mg",
                product_id: 11304,
                generic_name: "Cetirizine Hydrochloride [Oral] 10 mg",
                product_barcode: "145e4680601e4",
                product_unit: "10 mg",
                product_category: "Prescribe Medicine",
                product_sub_category: "Tablet",
                product_location: "medicare",
                dosage_form_name: "Tablet",
                dosage_strength: "10 mg",
                variations: [
                  {
                    variation_name: "1 Pc",
                    variation_id: "PVI1205250149",
                    is_default_variation: true,
                    qty_in_pcs: 0,
                    batch_number: "test2",
                    batch_name: "test2",
                    sku_number: "SKU1906250025",
                    product_cpu: 10,
                    received_quantity: 1,
                    purchase_vat: 0,
                    value_at_cost: 10,
                    net_purchase_value: 10,
                  },
                  {
                    variation_name: "1 Strip = 10 Pcs",
                    variation_id: "PVI1205250150",
                    is_default_variation: false,
                    qty_in_pcs: 0,
                    batch_number: "test2",
                    batch_name: "test2",
                    sku_number: "SKU1906250026",
                    product_cpu: 14,
                    received_quantity: 5,
                    purchase_vat: 0,
                    value_at_cost: 70,
                    net_purchase_value: 70,
                  },
                ],
                value_at_cost: 0,
                net_purchase_value: 0,
              },
              {
                product_name: "NAPA-250MG",
                product_id: 1222,
                generic_name: "Paracetamol 500 mg",
                product_barcode: null,
                product_unit: "250MG",
                product_category: "OTC Medicine",
                product_sub_category: "Fever",
                product_location: "medicare",
                dosage_form_name: null,
                dosage_strength: null,
                variations: [
                  {
                    variation_name: "NAPA-Pcs",
                    variation_id: "PVI2602250002",
                    is_default_variation: true,
                    qty_in_pcs: 15,
                    batch_number: "test",
                    batch_name: "test",
                    sku_number: "SKU1906250021",
                    product_cpu: 15.25,
                    received_quantity: 30,
                    purchase_vat: 0,
                    value_at_cost: 457.5,
                    net_purchase_value: 457.5,
                  },
                  {
                    variation_name: "Napa-M",
                    variation_id: "PVI2101250001",
                    is_default_variation: false,
                    qty_in_pcs: 0,
                    batch_number: "test2",
                    batch_name: "test2",
                    sku_number: "SKU1906250024",
                    product_cpu: 15.25,
                    received_quantity: 10,
                    purchase_vat: 0,
                    value_at_cost: 152.5,
                    net_purchase_value: 152.5,
                  },
                  {
                    variation_name: "Napa Strip",
                    variation_id: "PVI0801250001",
                    is_default_variation: false,
                    qty_in_pcs: 5,
                    batch_number: "test2",
                    batch_name: "test2",
                    sku_number: "SKU1906250022",
                    product_cpu: 15.25,
                    received_quantity: 40,
                    purchase_vat: 0,
                    value_at_cost: 610,
                    net_purchase_value: 610,
                  },
                  {
                    variation_name: "NAPA-Box",
                    variation_id: "PVI0203250001",
                    is_default_variation: false,
                    qty_in_pcs: 10,
                    batch_number: "test2",
                    batch_name: "test2",
                    sku_number: "SKU1906250023",
                    product_cpu: 15.25,
                    received_quantity: 50,
                    purchase_vat: 0,
                    value_at_cost: 762.5,
                    net_purchase_value: 762.5,
                  },
                ],
                value_at_cost: 0,
                net_purchase_value: 0,
              },
            ],
            total_value_at_cost: 2812.5,
            total_received_quantity: 139,
            total_product_cpu: 585,
            total_net_purchase_value: 2812.5,
            total_purchase_vat: 0,
          },
          {
            purchase_id: "POP1706250001",
            purchase_order_placed_id: 184,
            purchase_reference: "PO1706250001",
            purchase_date: "2025-06-17",
            purchase_time: "05:07:58.588145",
            posted_by: "HasanAdmin",
            additional_commission: 0,
            quantity: 20,
            bonus_quantity: 0,
            total_quantity: 20,
            products: [
              {
                product_name: "NAPA-250MG",
                product_id: 1222,
                generic_name: "Paracetamol 500 mg",
                product_barcode: null,
                product_unit: "250MG",
                product_category: "OTC Medicine",
                product_sub_category: "Fever",
                product_location: "medicare",
                dosage_form_name: null,
                dosage_strength: null,
                variations: [
                  {
                    variation_name: "NAPA-Pcs",
                    variation_id: "PVI2602250002",
                    is_default_variation: true,
                    qty_in_pcs: 15,
                    batch_number: "CB17062501",
                    batch_name: "CB17062501",
                    sku_number: "SKU1706250001",
                    product_cpu: 15.25,
                    received_quantity: 20,
                    purchase_vat: 0,
                    value_at_cost: 305,
                    net_purchase_value: 305,
                  },
                ],
                value_at_cost: 0,
                net_purchase_value: 0,
              },
            ],
            total_value_at_cost: 305,
            total_received_quantity: 20,
            total_product_cpu: 15.25,
            total_net_purchase_value: 305,
            total_purchase_vat: 0,
          },
          {
            purchase_id: "POP1706250002",
            purchase_order_placed_id: 185,
            purchase_reference: "PO1706250002",
            purchase_date: "2025-06-17",
            purchase_time: "06:12:52.269550",
            posted_by: "HasanAdmin",
            additional_commission: 0,
            quantity: 5,
            bonus_quantity: 0,
            total_quantity: 5,
            products: [
              {
                product_name: "NAPA-250MG",
                product_id: 1222,
                generic_name: "Paracetamol 500 mg",
                product_barcode: null,
                product_unit: "250MG",
                product_category: "OTC Medicine",
                product_sub_category: "Fever",
                product_location: "medicare",
                dosage_form_name: null,
                dosage_strength: null,
                variations: [
                  {
                    variation_name: "NAPA-Pcs",
                    variation_id: "PVI2602250002",
                    is_default_variation: true,
                    qty_in_pcs: 15,
                    batch_number: "CB1706252502",
                    batch_name: "CB1706252502",
                    sku_number: "SKU1706250003",
                    product_cpu: 15.25,
                    received_quantity: 5,
                    purchase_vat: 0,
                    value_at_cost: 76.25,
                    net_purchase_value: 76.25,
                  },
                ],
                value_at_cost: 0,
                net_purchase_value: 0,
              },
            ],
            total_value_at_cost: 76.25,
            total_received_quantity: 5,
            total_product_cpu: 15.25,
            total_net_purchase_value: 76.25,
            total_purchase_vat: 0,
          },
          {
            purchase_id: "POP1906250002",
            purchase_order_placed_id: 192,
            purchase_reference: "Purchased for Warehouse",
            purchase_date: "2025-06-19",
            purchase_time: "07:14:50.847429",
            posted_by: "SazzadAdmin",
            additional_commission: 0,
            quantity: 5,
            bonus_quantity: 0,
            total_quantity: 5,
            products: [
              {
                product_name: "BROFEX-100 ML",
                product_id: 11233,
                generic_name: null,
                product_barcode: "99e7fec5e9a44",
                product_unit: "100 ML",
                product_category: "OTC Medicine",
                product_sub_category: "Fever",
                product_location: "medicare",
                dosage_form_name: null,
                dosage_strength: null,
                variations: [
                  {
                    variation_name: "BROFEX-Tube",
                    variation_id: "PVI2605250001",
                    is_default_variation: false,
                    qty_in_pcs: 0,
                    batch_number: "B1FTP",
                    batch_name: "B1FTP",
                    sku_number: "SKU2605250016",
                    product_cpu: 5.66,
                    received_quantity: 5,
                    purchase_vat: 0,
                    value_at_cost: 28.3,
                    net_purchase_value: 28.3,
                  },
                ],
                value_at_cost: 0,
                net_purchase_value: 0,
              },
            ],
            total_value_at_cost: 28.3,
            total_received_quantity: 5,
            total_product_cpu: 5.66,
            total_net_purchase_value: 28.3,
            total_purchase_vat: 0,
          },
          {
            purchase_id: "POP1906250003",
            purchase_order_placed_id: 193,
            purchase_reference: "Purchased for Warehouse",
            purchase_date: "2025-06-19",
            purchase_time: "07:26:31.648977",
            posted_by: "SazzadAdmin",
            additional_commission: 0,
            quantity: 5,
            bonus_quantity: 5,
            total_quantity: 5,
            products: [
              {
                product_name: "BROFEX-100 ML",
                product_id: 11233,
                generic_name: null,
                product_barcode: "99e7fec5e9a44",
                product_unit: "100 ML",
                product_category: "OTC Medicine",
                product_sub_category: "Fever",
                product_location: "medicare",
                dosage_form_name: null,
                dosage_strength: null,
                variations: [
                  {
                    variation_name: "BROFEX-Tube",
                    variation_id: "PVI2605250001",
                    is_default_variation: false,
                    qty_in_pcs: 0,
                    batch_number: "B1FTP",
                    batch_name: "B1FTP",
                    sku_number: "SKU2605250016",
                    product_cpu: 0,
                    received_quantity: 10,
                    purchase_vat: 0,
                    value_at_cost: 0,
                    net_purchase_value: 0,
                  },
                ],
                value_at_cost: 0,
                net_purchase_value: 0,
              },
            ],
            total_value_at_cost: 0,
            total_received_quantity: 10,
            total_product_cpu: 0,
            total_net_purchase_value: 0,
            total_purchase_vat: 0,
          },
          {
            purchase_id: "POP1906250004",
            purchase_order_placed_id: 194,
            purchase_reference: "Purchased for Warehouse",
            purchase_date: "2025-06-19",
            purchase_time: "07:27:03.669453",
            posted_by: "SazzadAdmin",
            additional_commission: 0,
            quantity: 5,
            bonus_quantity: 5,
            total_quantity: 5,
            products: [
              {
                product_name: "BROFEX-100 ML",
                product_id: 11233,
                generic_name: null,
                product_barcode: "99e7fec5e9a44",
                product_unit: "100 ML",
                product_category: "OTC Medicine",
                product_sub_category: "Fever",
                product_location: "medicare",
                dosage_form_name: null,
                dosage_strength: null,
                variations: [
                  {
                    variation_name: "BROFEX-Tube",
                    variation_id: "PVI2605250001",
                    is_default_variation: false,
                    qty_in_pcs: 0,
                    batch_number: "B1FTP",
                    batch_name: "B1FTP",
                    sku_number: "SKU2605250016",
                    product_cpu: 0,
                    received_quantity: 10,
                    purchase_vat: 0,
                    value_at_cost: 0,
                    net_purchase_value: 0,
                  },
                ],
                value_at_cost: 0,
                net_purchase_value: 0,
              },
            ],
            total_value_at_cost: 0,
            total_received_quantity: 10,
            total_product_cpu: 0,
            total_net_purchase_value: 0,
            total_purchase_vat: 0,
          },
          {
            purchase_id: "POP1906250005",
            purchase_order_placed_id: 195,
            purchase_reference: "Purchased for Warehouse",
            purchase_date: "2025-06-19",
            purchase_time: "07:29:38.594650",
            posted_by: "SazzadAdmin",
            additional_commission: 0,
            quantity: 5,
            bonus_quantity: 5,
            total_quantity: 5,
            products: [
              {
                product_name: "BROFEX-100 ML",
                product_id: 11233,
                generic_name: null,
                product_barcode: "99e7fec5e9a44",
                product_unit: "100 ML",
                product_category: "OTC Medicine",
                product_sub_category: "Fever",
                product_location: "medicare",
                dosage_form_name: null,
                dosage_strength: null,
                variations: [
                  {
                    variation_name: "BROFEX-Tube",
                    variation_id: "PVI2605250001",
                    is_default_variation: false,
                    qty_in_pcs: 0,
                    batch_number: "B1FTP",
                    batch_name: "B1FTP",
                    sku_number: "SKU2605250016",
                    product_cpu: 0,
                    received_quantity: 10,
                    purchase_vat: 0,
                    value_at_cost: 0,
                    net_purchase_value: 0,
                  },
                ],
                value_at_cost: 0,
                net_purchase_value: 0,
              },
            ],
            total_value_at_cost: 0,
            total_received_quantity: 10,
            total_product_cpu: 0,
            total_net_purchase_value: 0,
            total_purchase_vat: 0,
          },
          {
            purchase_id: "POP1906250006",
            purchase_order_placed_id: 196,
            purchase_reference: "Purchased for Warehouse",
            purchase_date: "2025-06-19",
            purchase_time: "07:30:09.839414",
            posted_by: "SazzadAdmin",
            additional_commission: 0,
            quantity: 200,
            bonus_quantity: 5,
            total_quantity: 200,
            products: [
              {
                product_name: "BROFEX-100 ML",
                product_id: 11233,
                generic_name: null,
                product_barcode: "99e7fec5e9a44",
                product_unit: "100 ML",
                product_category: "OTC Medicine",
                product_sub_category: "Fever",
                product_location: "medicare",
                dosage_form_name: null,
                dosage_strength: null,
                variations: [
                  {
                    variation_name: "BROFEX-Tube",
                    variation_id: "PVI2605250001",
                    is_default_variation: false,
                    qty_in_pcs: 0,
                    batch_number: "B1FTP",
                    batch_name: "B1FTP",
                    sku_number: "SKU2605250016",
                    product_cpu: 5.38,
                    received_quantity: 205,
                    purchase_vat: 0,
                    value_at_cost: 1103.7,
                    net_purchase_value: 1103.7,
                  },
                ],
                value_at_cost: 0,
                net_purchase_value: 0,
              },
            ],
            total_value_at_cost: 1103.7,
            total_received_quantity: 205,
            total_product_cpu: 5.38,
            total_net_purchase_value: 1103.7,
            total_purchase_vat: 0,
          },
          {
            purchase_id: "POP1906250007",
            purchase_order_placed_id: 197,
            purchase_reference: "Purchased for Warehouse",
            purchase_date: "2025-06-19",
            purchase_time: "07:31:53.251567",
            posted_by: "SazzadAdmin",
            additional_commission: 0,
            quantity: 200,
            bonus_quantity: 5,
            total_quantity: 200,
            products: [
              {
                product_name: "BROFEX-100 ML",
                product_id: 11233,
                generic_name: null,
                product_barcode: "99e7fec5e9a44",
                product_unit: "100 ML",
                product_category: "OTC Medicine",
                product_sub_category: "Fever",
                product_location: "medicare",
                dosage_form_name: null,
                dosage_strength: null,
                variations: [
                  {
                    variation_name: "BROFEX-Tube",
                    variation_id: "PVI2605250001",
                    is_default_variation: false,
                    qty_in_pcs: 0,
                    batch_number: "B1FTP",
                    batch_name: "B1FTP",
                    sku_number: "SKU2605250016",
                    product_cpu: 5.38,
                    received_quantity: 205,
                    purchase_vat: 0,
                    value_at_cost: 1103.7,
                    net_purchase_value: 1103.7,
                  },
                ],
                value_at_cost: 0,
                net_purchase_value: 0,
              },
            ],
            total_value_at_cost: 1103.7,
            total_received_quantity: 205,
            total_product_cpu: 5.38,
            total_net_purchase_value: 1103.7,
            total_purchase_vat: 0,
          },
          {
            purchase_id: "POP1906250008",
            purchase_order_placed_id: 198,
            purchase_reference: "Purchased for Warehouse",
            purchase_date: "2025-06-19",
            purchase_time: "07:47:07.039187",
            posted_by: "SazzadAdmin",
            additional_commission: 0,
            quantity: 20,
            bonus_quantity: 5,
            total_quantity: 20,
            products: [
              {
                product_name: "BROFEX-100 ML",
                product_id: 11233,
                generic_name: null,
                product_barcode: "99e7fec5e9a44",
                product_unit: "100 ML",
                product_category: "OTC Medicine",
                product_sub_category: "Fever",
                product_location: "medicare",
                dosage_form_name: null,
                dosage_strength: null,
                variations: [
                  {
                    variation_name: "BROFEX-Tube",
                    variation_id: "PVI2605250001",
                    is_default_variation: false,
                    qty_in_pcs: 0,
                    batch_number: "B1FTP",
                    batch_name: "B1FTP",
                    sku_number: "SKU2605250016",
                    product_cpu: 3.4,
                    received_quantity: 25,
                    purchase_vat: 0,
                    value_at_cost: 84.9,
                    net_purchase_value: 84.9,
                  },
                ],
                value_at_cost: 0,
                net_purchase_value: 0,
              },
            ],
            total_value_at_cost: 84.9,
            total_received_quantity: 25,
            total_product_cpu: 3.4,
            total_net_purchase_value: 84.9,
            total_purchase_vat: 0,
          },
          {
            purchase_id: "POP1906250009",
            purchase_order_placed_id: 199,
            purchase_reference: "Purchased for Warehouse",
            purchase_date: "2025-06-19",
            purchase_time: "08:35:19.777240",
            posted_by: "SazzadAdmin",
            additional_commission: 0,
            quantity: 20,
            bonus_quantity: 5,
            total_quantity: 20,
            products: [
              {
                product_name: "BROFEX-100 ML",
                product_id: 11233,
                generic_name: null,
                product_barcode: "99e7fec5e9a44",
                product_unit: "100 ML",
                product_category: "OTC Medicine",
                product_sub_category: "Fever",
                product_location: "medicare",
                dosage_form_name: null,
                dosage_strength: null,
                variations: [
                  {
                    variation_name: "BROFEX-Tube",
                    variation_id: "PVI2605250001",
                    is_default_variation: false,
                    qty_in_pcs: 0,
                    batch_number: "B1FTP",
                    batch_name: "B1FTP",
                    sku_number: "SKU2605250016",
                    product_cpu: 3.4,
                    received_quantity: 25,
                    purchase_vat: 0,
                    value_at_cost: 84.9,
                    net_purchase_value: 84.9,
                  },
                ],
                value_at_cost: 0,
                net_purchase_value: 0,
              },
            ],
            total_value_at_cost: 84.9,
            total_received_quantity: 25,
            total_product_cpu: 3.4,
            total_net_purchase_value: 84.9,
            total_purchase_vat: 0,
          },
        ],
      },
      {
        supplier_id: 4,
        supplier_name: "A B GROUP",
        purchases: [
          {
            purchase_id: "POP1906250001",
            purchase_order_placed_id: 191,
            purchase_reference: "QA Testing Purpose",
            purchase_date: "2025-06-19",
            purchase_time: "06:52:25.449896",
            posted_by: "Shanto Kumar Saha",
            additional_commission: 0,
            quantity: 100,
            bonus_quantity: 100,
            total_quantity: 100,
            products: [
              {
                product_name: "Bashundhara Facial Tissue-30 Pcs",
                product_id: 11492,
                generic_name: null,
                product_barcode: "c97e9fadbad24",
                product_unit: "30 Pcs",
                product_category: "Toiletries",
                product_sub_category: "Tissue",
                product_location: "bodycare",
                dosage_form_name: null,
                dosage_strength: null,
                variations: [
                  {
                    variation_name: "Bashundhara Facial Tissue-Blue",
                    variation_id: "PVI0206250011",
                    is_default_variation: false,
                    qty_in_pcs: 5,
                    batch_number: "CB19062501",
                    batch_name: "CB19062501",
                    sku_number: "SKU1906250001",
                    product_cpu: 0,
                    received_quantity: 200,
                    purchase_vat: 0,
                    value_at_cost: 0,
                    net_purchase_value: 0,
                  },
                  {
                    variation_name: "test",
                    variation_id: "PVI0206250013",
                    is_default_variation: true,
                    qty_in_pcs: 20,
                    batch_number: "CB1906252502",
                    batch_name: "CB1906252502",
                    sku_number: "SKU1906250002",
                    product_cpu: 40,
                    received_quantity: 1000,
                    purchase_vat: 0,
                    value_at_cost: 40000,
                    net_purchase_value: 40000,
                  },
                  {
                    variation_name: "M",
                    variation_id: "PVI2705250009",
                    is_default_variation: false,
                    qty_in_pcs: 0,
                    batch_number: "CB1906252504",
                    batch_name: "CB1906252504",
                    sku_number: "SKU1906250004",
                    product_cpu: 19.6,
                    received_quantity: 1010,
                    purchase_vat: 0,
                    value_at_cost: 19800,
                    net_purchase_value: 19800,
                  },
                  {
                    variation_name: "Bashundhara Facial Tissue-Bottle",
                    variation_id: "PVI2705250008",
                    is_default_variation: false,
                    qty_in_pcs: 0,
                    batch_number: "CB1906252508",
                    batch_name: "CB1906252508",
                    sku_number: "SKU1906250008",
                    product_cpu: 30,
                    received_quantity: 1000,
                    purchase_vat: 0,
                    value_at_cost: 30000,
                    net_purchase_value: 30000,
                  },
                  {
                    variation_name: "Bashundhara Facial Tissue-Strip",
                    variation_id: "PVI2705250004",
                    is_default_variation: false,
                    qty_in_pcs: 0,
                    batch_number: "CB1906252503",
                    batch_name: "CB1906252503",
                    sku_number: "SKU1906250003",
                    product_cpu: 120,
                    received_quantity: 1000,
                    purchase_vat: 0,
                    value_at_cost: 120000,
                    net_purchase_value: 120000,
                  },
                  {
                    variation_name: "Final",
                    variation_id: "PVI0206250014",
                    is_default_variation: false,
                    qty_in_pcs: 10,
                    batch_number: "CB1906252507",
                    batch_name: "CB1906252507",
                    sku_number: "SKU1906250007",
                    product_cpu: 50,
                    received_quantity: 1000,
                    purchase_vat: 0,
                    value_at_cost: 50000,
                    net_purchase_value: 50000,
                  },
                  {
                    variation_name: "L Size",
                    variation_id: "PVI2705250003",
                    is_default_variation: false,
                    qty_in_pcs: 20,
                    batch_number: "CB1906252506",
                    batch_name: "CB1906252506",
                    sku_number: "SKU1906250006",
                    product_cpu: 40,
                    received_quantity: 1000,
                    purchase_vat: 0,
                    value_at_cost: 40000,
                    net_purchase_value: 40000,
                  },
                  {
                    variation_name: "Blue Test",
                    variation_id: "PVI0206250012",
                    is_default_variation: false,
                    qty_in_pcs: 100,
                    batch_number: "CB1906252505",
                    batch_name: "CB1906252505",
                    sku_number: "SKU1906250005",
                    product_cpu: 220,
                    received_quantity: 100,
                    purchase_vat: 0,
                    value_at_cost: 22000,
                    net_purchase_value: 22000,
                  },
                ],
                value_at_cost: 0,
                net_purchase_value: 0,
              },
              {
                product_name: "COCOLA EGG & CHICKEN NOODLES-150 GM",
                product_id: 11313,
                generic_name: null,
                product_barcode: "8941155013632",
                product_unit: "150 GM",
                product_category: "Bazar Sodai",
                product_sub_category: "Noodles",
                product_location: "food",
                dosage_form_name: null,
                dosage_strength: null,
                variations: [
                  {
                    variation_name: "1 Pcs",
                    variation_id: "PVI1805250002",
                    is_default_variation: true,
                    qty_in_pcs: 0,
                    batch_number: "CB1906252511",
                    batch_name: "CB1906252511",
                    sku_number: "SKU1906250011",
                    product_cpu: 30,
                    received_quantity: 1000,
                    purchase_vat: 0,
                    value_at_cost: 30000,
                    net_purchase_value: 30000,
                  },
                ],
                value_at_cost: 0,
                net_purchase_value: 0,
              },
              {
                product_name: "COCOLA EGG NOODLES-120 GM",
                product_id: 11312,
                generic_name: null,
                product_barcode: "8941155013502",
                product_unit: "120 GM",
                product_category: "Bazar Sodai",
                product_sub_category: "Noodles",
                product_location: "medicare",
                dosage_form_name: null,
                dosage_strength: null,
                variations: [
                  {
                    variation_name: "1 Pcs",
                    variation_id: "PVI1805250001",
                    is_default_variation: true,
                    qty_in_pcs: 0,
                    batch_number: "CB1906252512",
                    batch_name: "CB1906252512",
                    sku_number: "SKU1906250012",
                    product_cpu: 77,
                    received_quantity: 1000,
                    purchase_vat: 0,
                    value_at_cost: 77000,
                    net_purchase_value: 77000,
                  },
                ],
                value_at_cost: 0,
                net_purchase_value: 0,
              },
              {
                product_name: "COCOLA FROOTI LOOPS-70 GM",
                product_id: 11320,
                generic_name: null,
                product_barcode: "8941155003664",
                product_unit: "70 GM",
                product_category: "Food",
                product_sub_category: "Chocolate",
                product_location: "food",
                dosage_form_name: null,
                dosage_strength: null,
                variations: [
                  {
                    variation_name: "1 Pcs",
                    variation_id: "PVI1805250009",
                    is_default_variation: true,
                    qty_in_pcs: 0,
                    batch_number: "CB1906252513",
                    batch_name: "CB1906252513",
                    sku_number: "SKU1906250013",
                    product_cpu: 30,
                    received_quantity: 1000,
                    purchase_vat: 0,
                    value_at_cost: 30000,
                    net_purchase_value: 30000,
                  },
                ],
                value_at_cost: 0,
                net_purchase_value: 0,
              },
              {
                product_name: "COCOLA JUNIOR CUP CHICKEN CURRY NOODLES-40 GM",
                product_id: 11316,
                generic_name: null,
                product_barcode: "8941155001097",
                product_unit: "40 GM",
                product_category: "Bazar Sodai",
                product_sub_category: "Noodles",
                product_location: "food",
                dosage_form_name: null,
                dosage_strength: null,
                variations: [
                  {
                    variation_name: "1 Pcs",
                    variation_id: "PVI1805250005",
                    is_default_variation: true,
                    qty_in_pcs: 0,
                    batch_number: "CB1906252514",
                    batch_name: "CB1906252514",
                    sku_number: "SKU1906250014",
                    product_cpu: 68,
                    received_quantity: 1000,
                    purchase_vat: 0,
                    value_at_cost: 68000,
                    net_purchase_value: 68000,
                  },
                ],
                value_at_cost: 0,
                net_purchase_value: 0,
              },
              {
                product_name: "COCOLA MR. CHICKEN NOODLES-180 GM",
                product_id: 11318,
                generic_name: null,
                product_barcode: "8941155013687",
                product_unit: "180 GM",
                product_category: "Bazar Sodai",
                product_sub_category: "Noodles",
                product_location: "food",
                dosage_form_name: null,
                dosage_strength: null,
                variations: [
                  {
                    variation_name: "1 Pcs",
                    variation_id: "PVI1805250007",
                    is_default_variation: true,
                    qty_in_pcs: 0,
                    batch_number: "CB1906252515",
                    batch_name: "CB1906252515",
                    sku_number: "SKU1906250015",
                    product_cpu: 68,
                    received_quantity: 1000,
                    purchase_vat: 0,
                    value_at_cost: 68000,
                    net_purchase_value: 68000,
                  },
                ],
                value_at_cost: 0,
                net_purchase_value: 0,
              },
              {
                product_name: "COCOLA NOODLES-300 GM",
                product_id: 11314,
                generic_name: null,
                product_barcode: "8941155003442",
                product_unit: "300 GM",
                product_category: "Bazar Sodai",
                product_sub_category: "Noodles",
                product_location: "food",
                dosage_form_name: null,
                dosage_strength: null,
                variations: [
                  {
                    variation_name: "1 Pcs",
                    variation_id: "PVI1805250003",
                    is_default_variation: true,
                    qty_in_pcs: 0,
                    batch_number: "CB1906252516",
                    batch_name: "CB1906252516",
                    sku_number: "SKU1906250016",
                    product_cpu: 68,
                    received_quantity: 1000,
                    purchase_vat: 0,
                    value_at_cost: 68000,
                    net_purchase_value: 68000,
                  },
                ],
                value_at_cost: 0,
                net_purchase_value: 0,
              },
              {
                product_name: "COCOLA SUPER EGG AND CHICKEN NOODLES-500 GM",
                product_id: 11317,
                generic_name: null,
                product_barcode: "8941155013731",
                product_unit: "500 GM",
                product_category: "Bazar Sodai",
                product_sub_category: "Noodles",
                product_location: "food",
                dosage_form_name: null,
                dosage_strength: null,
                variations: [
                  {
                    variation_name: "1 Pcs",
                    variation_id: "PVI1805250006",
                    is_default_variation: true,
                    qty_in_pcs: 0,
                    batch_number: "CB1906252517",
                    batch_name: "CB1906252517",
                    sku_number: "SKU1906250017",
                    product_cpu: 44,
                    received_quantity: 1000,
                    purchase_vat: 0,
                    value_at_cost: 44000,
                    net_purchase_value: 44000,
                  },
                ],
                value_at_cost: 0,
                net_purchase_value: 0,
              },
              {
                product_name: "COCOLA WAFER ROLL-280 GM",
                product_id: 11321,
                generic_name: null,
                product_barcode: "8941155008188",
                product_unit: "280 GM",
                product_category: "Food",
                product_sub_category: "Wafer",
                product_location: "food",
                dosage_form_name: null,
                dosage_strength: null,
                variations: [
                  {
                    variation_name: "1 Pcs",
                    variation_id: "PVI1805250010",
                    is_default_variation: true,
                    qty_in_pcs: 0,
                    batch_number: "CB1906252518",
                    batch_name: "CB1906252518",
                    sku_number: "SKU1906250018",
                    product_cpu: 44,
                    received_quantity: 1000,
                    purchase_vat: 0,
                    value_at_cost: 44000,
                    net_purchase_value: 44000,
                  },
                ],
                value_at_cost: 0,
                net_purchase_value: 0,
              },
              {
                product_name: "Demo-None",
                product_id: 11503,
                generic_name: null,
                product_barcode: "9b26b270d2424",
                product_unit: null,
                product_category: "OTC Medicine",
                product_sub_category: "Acidity",
                product_location: "bodycare",
                dosage_form_name: null,
                dosage_strength: null,
                variations: [
                  {
                    variation_name: "Blue",
                    variation_id: "PVI0406250018",
                    is_default_variation: true,
                    qty_in_pcs: 0,
                    batch_number: "CB1906252519",
                    batch_name: "CB1906252519",
                    sku_number: "SKU1906250019",
                    product_cpu: 700,
                    received_quantity: 1000,
                    purchase_vat: 0,
                    value_at_cost: 700000,
                    net_purchase_value: 700000,
                  },
                  {
                    variation_name: "Test Vr",
                    variation_id: "PVI0406250019",
                    is_default_variation: false,
                    qty_in_pcs: 10,
                    batch_number: "CB1906252520",
                    batch_name: "CB1906252520",
                    sku_number: "SKU1906250020",
                    product_cpu: 80,
                    received_quantity: 1000,
                    purchase_vat: 0,
                    value_at_cost: 80000,
                    net_purchase_value: 80000,
                  },
                ],
                value_at_cost: 0,
                net_purchase_value: 0,
              },
              {
                product_name: "COCOLA BIG BAZAR NOODLES-600 GM-14 PCS",
                product_id: 11319,
                generic_name: null,
                product_barcode: "8941155013571",
                product_unit: "600 GM-14 PCS",
                product_category: "Bazar Sodai",
                product_sub_category: "Noodles",
                product_location: "food",
                dosage_form_name: null,
                dosage_strength: null,
                variations: [
                  {
                    variation_name: "1 Pcs",
                    variation_id: "PVI1805250008",
                    is_default_variation: true,
                    qty_in_pcs: 0,
                    batch_number: "CB1906252509",
                    batch_name: "CB1906252509",
                    sku_number: "SKU1906250009",
                    product_cpu: 77,
                    received_quantity: 1000,
                    purchase_vat: 0,
                    value_at_cost: 77000,
                    net_purchase_value: 77000,
                  },
                ],
                value_at_cost: 0,
                net_purchase_value: 0,
              },
              {
                product_name: "COCOLA BOWL BEEF BHUNA NOODLES-70 GM",
                product_id: 11315,
                generic_name: null,
                product_barcode: "8941155032701",
                product_unit: "70 GM",
                product_category: "Bazar Sodai",
                product_sub_category: "Noodles",
                product_location: "food",
                dosage_form_name: null,
                dosage_strength: null,
                variations: [
                  {
                    variation_name: "1 Pcs",
                    variation_id: "PVI1805250004",
                    is_default_variation: true,
                    qty_in_pcs: 0,
                    batch_number: "CB1906252510",
                    batch_name: "CB1906252510",
                    sku_number: "SKU1906250010",
                    product_cpu: 30,
                    received_quantity: 1000,
                    purchase_vat: 0,
                    value_at_cost: 30000,
                    net_purchase_value: 30000,
                  },
                ],
                value_at_cost: 0,
                net_purchase_value: 0,
              },
            ],
            total_value_at_cost: 1637800,
            total_received_quantity: 18310,
            total_product_cpu: 1835.6,
            total_net_purchase_value: 1637800,
            total_purchase_vat: 0,
          },
        ],
      },
    ],
  },
  status: 200,
  statusText: "",
  headers: {
    "content-length": "29013",
    "content-type": "application/json",
  },
  config: {
    transitional: {
      silentJSONParsing: true,
      forcedJSONParsing: true,
      clarifyTimeoutError: false,
    },
    adapter: ["xhr", "http"],
    transformRequest: [null],
    transformResponse: [null],
    timeout: 0,
    xsrfCookieName: "XSRF-TOKEN",
    xsrfHeaderName: "X-XSRF-TOKEN",
    maxContentLength: -1,
    maxBodyLength: -1,
    env: {},
    headers: {
      Accept: "application/json, text/plain, */*",
      Authorization:
        "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzUwOTEwMTg4LCJpYXQiOjE3NTA4MjM3ODgsImp0aSI6IjY4OThhMDYyNzExMjQxYjc5MWMxNTk3NGU4Yjc0MWY3IiwidXNlcl9pZCI6NDY1Mn0.JAAXSB9xY8rqN2A5emlgtZev_Y95-mKVPsGOhPRaXys",
    },
    method: "get",
    url: "https://cbapi.meherab.xyz/api/v2/report/purchase-order/supplier-wise-purchase-report/?from_date=2025-06-13&to_date=2025-06-20",
  },
  request: {},
};

var reportTitle = "PURCHASE ORDER CHALLAN";

const Home = () => {
  return (
    <div>
      <div className="flex justify-center items-center mt-[100px]">
        <div className="bg-[#f2f3f8] p-8 rounded-md flex flex-col justify-center items-center">
          <button
            type="button"
            className="px-[37px] py-[12px] bg-gradient-to-b from-[#D13F96] to-[#833586] text-white rounded-[5px] text-lg font-bold leading-[21.48px] cursor-pointer"
            onClick={() => SupplierRcvReportPdf(data, reportTitle)}
          >
            Generate PDF
          </button>
        </div>
      </div>
    </div>
  );
};

export default Home;
